name: Daily Pipeline

on:
  workflow_dispatch:

  schedule:
    - cron: '13 4 * * *'

jobs:
  run-daily-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: ./.github/actions/setup_python_env

      - name: Run daily pipeline
        uses: ./.github/actions/run_pipeline
        with:
          script: run_daily_pipeline.py
          hopsworks_api_key: ${{ secrets.HOPSWORKS_API_KEY }}