name: Daily Model Training Pipeline

on:
  workflow_dispatch:

  schedule:
    - cron: '37 4 * * *'

jobs:
  run-model_training-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python environment
        uses: ./.github/actions/setup_python_env

      - name: Run model training pipeline
        uses: ./.github/actions/run_pipeline
        with:
          script: run_model_training.py
          hopsworks_api_key: ${{ secrets.HOPSWORKS_API_KEY }}