name: Daily Recovery

on:
  workflow_dispatch:

  schedule:
    - cron: '23 0 * * *'

jobs:
  run-daily-recovery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: ./.github/actions/setup_python_env

      - name: Run daily recovery
        uses: ./.github/actions/run_pipeline
        with:
          script: run_daily_recovery.py
          hopsworks_api_key: ${{ secrets.HOPSWORKS_API_KEY }}